### ISSUE TITLE
Zephyr Stars is not-quite-live, but close

### ISSUE THREAD

**Issue by jpn--** [ZephyrTransport/zephyr-stars#1]
Hi everybody!  We're looking to replace the old Zephyr "code repository" with something like this.  Feel free to go to town "starring" things you like on GitHub.  Note this is pretty low-tech and not a "live" updated list -- someone (me) needs to run the script manually and push the updated list.  To add names to the `known-users.yml`, you can just make a pull request.

@bstabler
@DavidOry
@billyc
@lmz
@dkyleward
@e-lo
@mmilkovits
@leta-huntsinger
@mike-mahut
@danielsclint
@timothyb0912
@cgkcmo
@JonathanEhrlichMC
@pedrocamargo
@krishnan-viswanathan
@AndrewTheTM
@gregmacfarlane
@Ennazus
@josiekre
@jkpdunbar
@gregerhardt
@rosellapicado
@sramming
@moh-salah
@dflynn-volpe

**Comment by josiekre** [comment]
This is a pretty nifty solution. Kudos!

**Comment by jpn--** [comment]
[Zephyr Stars](https://zephyrtransport.org/stars/) is now auto-updated nightly.  Go star something good and see for yourself!
