### ISSUE TITLE
transfer this to ZephyrTransport org?

### ISSUE THREAD

**Issue by jpn--** [ZephyrTransport/zephyr-stars#3]
If I am made able to create new repos on ZephyrTransport, I can move this repository there.

@billyc @e-lo

**Comment by billyc** [comment]
@e-lo could you add Jeff and myself as owners of the ZephyrTransport org? Otherwise you have to do all the admin ;-)

**Comment by e-lo** [comment]
I added Jeff as an "owner" although all members can make repos. B, I added
you as an owner as well.

**Comment by jpn--** [comment]
@e-lo Thanks!
